FST-68 Remove system-user related functionality
folio-org/folio-service-tools pull request #109
Opened 2023-10-27 05:08 UTC by GeloPakDev1

### Purpose
Remove system-user related functionality

### Approach
Investigation based on the functionality included from this PR("https://github.com/folio-org/folio-spring-support/pull/107/files") and dependecies which can occur in other modules

### Learning
- Investigate classes and methods from the PR mentioned above which contained in "folio-service-tools" 
- Usage of classes and methods from the "folio-spring-support" in other modules

2023-10-27 10:09 UTC, viacheslavkol commented on folio-service-tools-spring-dev/src/main/java/org/folio/spring/tools/kafka/KafkaScopedExecutionService.java
> -public class KafkaScopedExecutionService {
Why was this one removed? I can't see it in folio-spring-support

2023-10-27 10:09 UTC, viacheslavkol commented on folio-service-tools-spring-dev/src/main/java/org/folio/spring/tools/kafka/TenantIdCheckInterceptor.java
> -public class TenantIdCheckInterceptor implements ProducerInterceptor<String, String> {
Why was this one removed? I can't see it in folio-spring-support

2023-10-27 10:24 UTC, psmagin requested changes
1. Update NEWS file
2. Change the version in pom.xml to next major one as this is a breaking change.
3. While you will squash ane merge this PR please follow conventional commit format described on a page: https://wiki.folio.org/display/FOLIJET/Conventional+Commit+Initiative. It's required to have in a commit message an issue number. Please reach me directly if any help with commit message needed.

2023-10-30 08:58 UTC, psmagin requested changes

2023-10-30 08:58 UTC, psmagin commented on NEWS.md
> -## v3.2.0 In progress
Please back it into "In progress" and v4.0.0

2023-10-30 08:58 UTC, psmagin commented on folio-service-tools-spring-dev/pom.xml
> -    <version>3.2.0-SNAPSHOT</version>
It should be 4.0.0-SNAPSHOT

2023-10-30 08:58 UTC, psmagin commented on folio-service-tools-spring-dev/pom.xml
> -    <version>3.2.0-SNAPSHOT</version>
all pom.xml should be updated with this new version

2023-10-30 13:15 UTC, psmagin approved these changes

2023-11-01 09:07 UTC, merged