MODELINKS-87: Added delete kafka topic method
folio-org/folio-service-tools pull request #94
Opened 2023-05-26 07:13 UTC by hasanepam

### Purpose
Add kafka topic deletion by tenant id logic

### Approach
Added kafka topic deletion by tenant id method

### Learning
[MODELINKS-87](https://issues.folio.org/browse/MODELINKS-87)

2023-05-26 09:18 UTC, psmagin requested changes
Also, you have to create an additional ticket in the folio-service-tools project in Jira and use it for this work in the repository.

2023-05-26 09:18 UTC, psmagin commented on folio-service-tools-spring-dev/src/main/java/org/folio/spring/tools/kafka/KafkaAdminService.java
> +                                                             .toList();
```suggestion
    List<String> topicsToDelete = kafkaProperties.getTopics().stream()
      .map(FolioKafkaProperties.KafkaTopic::getName)
      .filter(name -> name.startsWith(FolioEnvironment.getFolioEnvName() + "." + tenantId + "."))
      .toList();
```
You could use ENV variable + tenantId to identify the start of the topic name.

2023-05-26 09:18 UTC, psmagin commented on folio-service-tools-spring-dev/src/main/java/org/folio/spring/tools/kafka/KafkaAdminService.java
> +                                                             .toList();
But in the same situation, you will delete all topics that have tenant id in their name. But you should delete only topics that the current module is creating on startup.

2023-05-26 09:18 UTC, psmagin commented on folio-service-tools-spring-dev/src/main/java/org/folio/spring/tools/kafka/KafkaAdminService.java
> +                                                             .toList();
Use 
`var configTopics = kafkaProperties.getTopics();` to get list of topics
and use 
`getTenantTopicName(topic.getName(), tenantId)` to get full topic name for current tenant

2023-05-26 13:39 UTC, psmagin requested changes

2023-05-26 13:39 UTC, psmagin commented on folio-service-tools-spring-dev/src/main/java/org/folio/spring/tools/kafka/KafkaAdminService.java
> +  public void deleteTopicsByTenant(String tenantId) {
```suggestion
  public void deleteTopics(String tenantId) {
```
I suggest to be consistent with `createTopics`

2023-05-26 13:39 UTC, psmagin commented on folio-service-tools-spring-dev/src/main/java/org/folio/spring/tools/kafka/KafkaAdminService.java
> +      .map(topic->getTenantTopicName(topic.getName(), tenantId))
```suggestion
      .map(topic -> getTenantTopicName(topic.getName(), tenantId))
```

2023-05-26 13:39 UTC, psmagin commented on folio-service-tools-spring-dev/src/main/java/org/folio/spring/tools/kafka/KafkaAdminService.java
> +      .filter(name -> name.startsWith(FolioEnvironment.getFolioEnvName() + "." + tenantId + "."))
There is no need for this line because all strings will startsWith this condition as you use `getTenantTopicName` method

2023-05-29 11:23 UTC, viacheslavkol approved these changes

2023-05-29 11:23 UTC, viacheslavkol commented on folio-service-tools-spring-dev/src/main/java/org/folio/spring/tools/kafka/KafkaAdminService.java
> +      .map(topic -> toKafkaTopic(topic, tenantId)).toList();
I'd be better to have ".toList()" on a newline

2023-05-30 07:42 UTC, Shans-Kaluhin approved these changes

2023-06-06 10:31 UTC, psmagin approved these changes

2023-06-06 11:05 UTC, merged